export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

const RootLayout = ({ children }: { readonly children: React.ReactNode }) => {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
};

export default RootLayout;
